import { useState } from "react";
import * as api from "../../lib/api";

interface AiNarrativeEditorProps {
  version: api.ProposalVersion;
  editable: boolean;
  token: string;
  onSaved: (v: api.ProposalVersion) => void;
}

export function AiNarrativeEditor({
  version,
  editable,
  token,
  onSaved,
}: AiNarrativeEditorProps) {
  const [draft, setDraft] = useState<
    (api.NarrativeOutput & { provider: string; model: string }) | null
  >(version.narrative_json || null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Check if dirty (different from version.narrative_json)
  const isDirty =
    draft !== null &&
    JSON.stringify(draft) !== JSON.stringify(version.narrative_json);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.generateProposalNarrative(token, version.id);
      setDraft({
        executive_summary: res.executive_summary,
        recommended_approach: res.recommended_approach,
        scope: res.scope,
        assumptions_exclusions: res.assumptions_exclusions,
        next_steps: res.next_steps,
        email_draft: res.email_draft,
        provider: res.provider,
        model: res.model,
      });
    } catch (err: any) {
      setError(err.message || "Failed to generate narrative");
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!draft) return;
    setSaving(true);
    try {
      const updated = await api.saveProposalVersionNarrative(
        token,
        version.id,
        draft,
      );
      setDraft(updated.narrative_json);
      onSaved(updated);
    } catch (err: any) {
      setError(err.message || "Failed to save narrative");
    } finally {
      setSaving(false);
    }
  };

  const updateField = (field: keyof api.NarrativeOutput, value: any) => {
    if (!draft) return;
    setDraft({ ...draft, [field]: value });
  };

  const hasLines = version.content_json.lines.length > 0;

  if (!editable && !version.narrative_json) {
    return null;
  }

  return (
    <div className="mt-8 border border-navy-800 bg-navy-900 rounded-lg p-6">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-semibold text-navy-50">
          AI Proposal Narrative
        </h2>
        {editable && (
          <button
            onClick={handleGenerate}
            disabled={!hasLines || loading}
            className="px-4 py-2 bg-navy-800 text-lime-400 border border-lime-400/30 rounded hover:bg-navy-700 disabled:opacity-50"
          >
            {loading ? "Generating..." : "Generate draft"}
          </button>
        )}
      </div>

      {error && (
        <div
          role="alert"
          className="mb-6 p-4 bg-red-900/50 border border-red-500/50 text-red-200 rounded flex justify-between items-center"
        >
          <span>{error}</span>
          <button
            onClick={handleGenerate}
            className="px-3 py-1 bg-red-800 rounded hover:bg-red-700"
          >
            Retry
          </button>
        </div>
      )}

      {draft && (
        <div className="space-y-6">
          <div className="flex justify-between items-center bg-navy-950 p-3 rounded text-sm text-navy-300">
            <div>
              {draft.provider === "openrouter" && "Generated by OpenRouter"}
              {draft.provider === "ollama" && "Generated locally with Ollama"}
              {draft.provider !== "openrouter" &&
                draft.provider !== "ollama" &&
                `Generated by ${draft.provider}`}
            </div>
            <div className="text-amber-400/80">
              Draft AI Content — Requires human review
            </div>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-navy-300 text-sm mb-1">
                Executive Summary
              </label>
              <textarea
                value={draft.executive_summary}
                onChange={(e) =>
                  updateField("executive_summary", e.target.value)
                }
                disabled={!editable}
                className="w-full bg-navy-950 border border-navy-700 rounded p-3 text-navy-50 min-h-[100px] disabled:opacity-75"
              />
            </div>
            <div>
              <label className="block text-navy-300 text-sm mb-1">
                Recommended Approach
              </label>
              <textarea
                value={draft.recommended_approach}
                onChange={(e) =>
                  updateField("recommended_approach", e.target.value)
                }
                disabled={!editable}
                className="w-full bg-navy-950 border border-navy-700 rounded p-3 text-navy-50 min-h-[100px] disabled:opacity-75"
              />
            </div>
            <div>
              <label className="block text-navy-300 text-sm mb-1">Scope</label>
              <textarea
                value={draft.scope}
                onChange={(e) => updateField("scope", e.target.value)}
                disabled={!editable}
                className="w-full bg-navy-950 border border-navy-700 rounded p-3 text-navy-50 min-h-[100px] disabled:opacity-75"
              />
            </div>

            <StringListEditor
              label="Assumptions & Exclusions"
              items={draft.assumptions_exclusions}
              editable={editable}
              onChange={(items) => updateField("assumptions_exclusions", items)}
            />

            <StringListEditor
              label="Next Steps"
              items={draft.next_steps}
              editable={editable}
              onChange={(items) => updateField("next_steps", items)}
            />

            <div>
              <label className="block text-navy-300 text-sm mb-1">
                Email Draft
              </label>
              <textarea
                value={draft.email_draft}
                onChange={(e) => updateField("email_draft", e.target.value)}
                disabled={!editable}
                className="w-full bg-navy-950 border border-navy-700 rounded p-3 text-navy-50 min-h-[150px] disabled:opacity-75 font-mono text-sm"
              />
            </div>
          </div>

          {editable && (
            <div className="flex justify-end pt-4">
              <button
                onClick={handleSave}
                disabled={!isDirty || saving}
                className="px-6 py-2 bg-lime-400 text-navy-950 font-medium rounded hover:bg-lime-500 disabled:opacity-50 disabled:bg-navy-700 disabled:text-navy-300"
              >
                {saving ? "Saving..." : "Save"}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function StringListEditor({
  label,
  items,
  editable,
  onChange,
}: {
  label: string;
  items: string[];
  editable: boolean;
  onChange: (items: string[]) => void;
}) {
  return (
    <div>
      <label className="block text-navy-300 text-sm mb-2">{label}</label>
      <div className="space-y-2">
        {items.map((item, idx) => (
          <div key={idx} className="flex gap-2">
            <input
              type="text"
              value={item}
              onChange={(e) => {
                const newItems = [...items];
                newItems[idx] = e.target.value;
                onChange(newItems);
              }}
              disabled={!editable}
              className="flex-1 bg-navy-950 border border-navy-700 rounded p-2 text-navy-50 disabled:opacity-75"
            />
            {editable && (
              <button
                onClick={() => {
                  const newItems = [...items];
                  newItems.splice(idx, 1);
                  onChange(newItems);
                }}
                className="px-3 bg-navy-800 text-red-400 border border-navy-700 rounded hover:bg-navy-700"
                aria-label="Remove item"
              >
                ×
              </button>
            )}
          </div>
        ))}
        {editable && (
          <button
            onClick={() => onChange([...items, ""])}
            className="text-sm text-lime-400 hover:text-lime-300"
          >
            + Add item
          </button>
        )}
      </div>
    </div>
  );
}
