import { Sparkles, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CARD_CLASSES } from "@/components/ui/variants";
import { cn } from "@/lib/utils";
import * as api from "../../lib/api";
import { ApiError, describeError } from "../../lib/errors";

type NarrativeDraft = api.NarrativeOutput & { provider: string; model: string };

type EditorError =
  | { kind: "generate"; message: string; retryable: boolean }
  | { kind: "save"; message: string; retryable: boolean };

// Provenance for text a person wrote from scratch after AI drafting failed or
// wasn't wanted (docs/runbooks/ai-provider-failure.md step 5).
const MANUAL_PROVIDER = "manual";

const BLANK_MANUAL_DRAFT: NarrativeDraft = {
  executive_summary: "",
  recommended_approach: "",
  scope: "",
  assumptions_exclusions: [],
  next_steps: [],
  email_draft: "",
  provider: MANUAL_PROVIDER,
  model: "none",
};

const LABEL = "mb-1 block text-sm text-muted-foreground";
// AI actions use the cyan info colour, keeping lime for human decisions.
const AI_BUTTON =
  "border-cyan-400/40 bg-cyan-400/10 text-info-foreground hover:bg-cyan-400/20";

// The API reports provider failures tersely ("Provider timeout"); say what
// happened in the user's terms. Status codes from apps/api/app/api/ai.py.
function describeGenerateError(
  err: unknown,
): Omit<EditorError, "kind"> & { canWriteManually: boolean } {
  const status = err instanceof ApiError ? err.status : null;
  switch (status) {
    case 504:
      return {
        message: "The AI provider took too long to respond.",
        retryable: true,
        canWriteManually: true,
      };
    case 502:
      return {
        message: "The AI provider sent back a draft we couldn't use.",
        retryable: true,
        canWriteManually: true,
      };
    case 500:
      return {
        message: "AI drafting isn't set up on this server.",
        retryable: false,
        canWriteManually: true,
      };
    case 400:
      return {
        message: "Add at least one package line before drafting.",
        retryable: false,
        canWriteManually: false,
      };
    case 403:
      return {
        ...describeError(err, { action: "draft proposal narratives" }),
        canWriteManually: false,
      };
    default:
      return {
        message: "Couldn't reach the AI provider.",
        retryable: true,
        canWriteManually: true,
      };
  }
}

function providerLabel(provider: string): string {
  switch (provider) {
    case "openrouter":
      return "Generated by OpenRouter";
    case "ollama":
      return "Generated locally with Ollama";
    case MANUAL_PROVIDER:
      return "Written manually";
    default:
      return `Generated by ${provider}`;
  }
}

interface AiNarrativeEditorProps {
  version: api.ProposalVersion;
  editable: boolean;
  token: string;
  onSaved: (v: api.ProposalVersion) => void;
}

export function AiNarrativeEditor({
  version,
  editable,
  token,
  onSaved,
}: AiNarrativeEditorProps) {
  const [draft, setDraft] = useState<NarrativeDraft | null>(
    version.narrative_json || null,
  );
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<EditorError | null>(null);
  const [canWriteManually, setCanWriteManually] = useState(false);

  const isDirty =
    draft !== null &&
    JSON.stringify(draft) !== JSON.stringify(version.narrative_json);

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const res = await api.generateProposalNarrative(token, version.id);
      setDraft({
        executive_summary: res.executive_summary,
        recommended_approach: res.recommended_approach,
        scope: res.scope,
        assumptions_exclusions: res.assumptions_exclusions,
        next_steps: res.next_steps,
        email_draft: res.email_draft,
        provider: res.provider,
        model: res.model,
      });
      toast.success("AI draft ready. Review it before saving.");
    } catch (err) {
      // Whatever is already in the editor stays put; a failed draft never
      // clears existing content (runbook step 5).
      const described = describeGenerateError(err);
      setError({
        kind: "generate",
        message: described.message,
        retryable: described.retryable,
      });
      setCanWriteManually(described.canWriteManually);
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!draft) return;
    setSaving(true);
    setError(null);
    try {
      const updated = await api.saveProposalVersionNarrative(
        token,
        version.id,
        draft,
      );
      setDraft(updated.narrative_json);
      onSaved(updated);
      toast.success("Narrative saved");
    } catch (err) {
      const described = describeError(err, { action: "save the narrative" });
      setError({ kind: "save", ...described });
      toast.error(described.message);
    } finally {
      setSaving(false);
    }
  };

  const handleWriteManually = () => {
    setError(null);
    setDraft(BLANK_MANUAL_DRAFT);
  };

  const updateField = <K extends keyof api.NarrativeOutput>(
    field: K,
    value: api.NarrativeOutput[K],
  ) => {
    if (!draft) return;
    setDraft({ ...draft, [field]: value });
  };

  const hasLines = version.content_json.lines.length > 0;

  if (!editable && !version.narrative_json) {
    return null;
  }

  const showWriteManually =
    editable && error?.kind === "generate" && canWriteManually && !draft;

  return (
    <section className={cn(CARD_CLASSES, "mt-8 p-4 sm:p-6")}>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-semibold text-foreground">
            AI proposal narrative
          </h2>
          <Badge variant="info">
            <Sparkles aria-hidden="true" />
            AI
          </Badge>
        </div>
        {editable && (
          <Button
            variant="outline"
            onClick={() => void handleGenerate()}
            disabled={!hasLines || generating}
            className={AI_BUTTON}
          >
            <Sparkles aria-hidden="true" />
            {generating ? "Generating…" : "Generate draft"}
          </Button>
        )}
      </div>

      {error && (
        <div
          role="alert"
          className="mb-6 flex flex-col gap-3 rounded-md border border-red-500/30 bg-red-500/10 p-4 sm:flex-row sm:items-center sm:justify-between"
        >
          <div>
            <p className="text-sm text-destructive-foreground">
              {error.message}
            </p>
            {showWriteManually && (
              <p className="mt-1 text-sm text-muted-foreground">
                You can try again, or write the narrative yourself.
              </p>
            )}
          </div>
          <div className="flex shrink-0 flex-wrap gap-2">
            {error.retryable && (
              <Button
                variant="outline"
                onClick={() =>
                  void (error.kind === "save" ? handleSave() : handleGenerate())
                }
              >
                Retry
              </Button>
            )}
            {showWriteManually && (
              <Button variant="outline" onClick={handleWriteManually}>
                Write it yourself
              </Button>
            )}
          </div>
        </div>
      )}

      {draft && (
        <div className="space-y-6">
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-border bg-background p-3">
            <Badge
              variant={draft.provider === MANUAL_PROVIDER ? "outline" : "info"}
            >
              {providerLabel(draft.provider)}
            </Badge>
            {draft.provider !== MANUAL_PROVIDER && (
              <Badge variant="warning">
                Draft AI Content — Requires human review
              </Badge>
            )}
          </div>

          <div className="space-y-4">
            <div>
              <label htmlFor="narrative-executive-summary" className={LABEL}>
                Executive summary
              </label>
              <Textarea
                id="narrative-executive-summary"
                value={draft.executive_summary}
                onChange={(e) =>
                  updateField("executive_summary", e.target.value)
                }
                disabled={!editable}
                className="min-h-[100px] text-base sm:text-sm"
              />
            </div>
            <div>
              <label htmlFor="narrative-recommended-approach" className={LABEL}>
                Recommended approach
              </label>
              <Textarea
                id="narrative-recommended-approach"
                value={draft.recommended_approach}
                onChange={(e) =>
                  updateField("recommended_approach", e.target.value)
                }
                disabled={!editable}
                className="min-h-[100px] text-base sm:text-sm"
              />
            </div>
            <div>
              <label htmlFor="narrative-scope" className={LABEL}>
                Scope
              </label>
              <Textarea
                id="narrative-scope"
                value={draft.scope}
                onChange={(e) => updateField("scope", e.target.value)}
                disabled={!editable}
                className="min-h-[100px] text-base sm:text-sm"
              />
            </div>

            <StringListEditor
              label="Assumptions and exclusions"
              items={draft.assumptions_exclusions}
              editable={editable}
              onChange={(items) => updateField("assumptions_exclusions", items)}
            />

            <StringListEditor
              label="Next steps"
              items={draft.next_steps}
              editable={editable}
              onChange={(items) => updateField("next_steps", items)}
            />

            <div>
              <label htmlFor="narrative-email-draft" className={LABEL}>
                Email draft
              </label>
              <Textarea
                id="narrative-email-draft"
                value={draft.email_draft}
                onChange={(e) => updateField("email_draft", e.target.value)}
                disabled={!editable}
                className="min-h-[150px] font-mono"
              />
            </div>
          </div>

          {editable && (
            <div className="flex justify-end pt-4">
              <Button
                onClick={() => void handleSave()}
                disabled={!isDirty || saving}
                className="px-6"
              >
                {saving ? "Saving…" : "Save"}
              </Button>
            </div>
          )}
        </div>
      )}
    </section>
  );
}

function StringListEditor({
  label,
  items,
  editable,
  onChange,
}: {
  label: string;
  items: string[];
  editable: boolean;
  onChange: (items: string[]) => void;
}) {
  return (
    <fieldset>
      <legend className="mb-2 block text-sm text-muted-foreground">
        {label}
      </legend>
      <div className="space-y-2">
        {items.map((item, idx) => (
          <div key={idx} className="flex gap-2">
            <Input
              type="text"
              value={item}
              aria-label={`${label}, item ${idx + 1}`}
              onChange={(e) => {
                const newItems = [...items];
                newItems[idx] = e.target.value;
                onChange(newItems);
              }}
              disabled={!editable}
              className="flex-1"
            />
            {editable && (
              <Button
                variant="outline"
                size="icon"
                onClick={() => {
                  const newItems = [...items];
                  newItems.splice(idx, 1);
                  onChange(newItems);
                }}
                className="hover:text-destructive-foreground"
                aria-label={`Remove ${label.toLowerCase()} item ${idx + 1}`}
              >
                <X />
              </Button>
            )}
          </div>
        ))}
        {editable && (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => onChange([...items, ""])}
          >
            + Add item
          </Button>
        )}
      </div>
    </fieldset>
  );
}
