import { useState } from "react";
import * as api from "../../lib/api";
import { ApiError, describeError } from "../../lib/errors";

type NarrativeDraft = api.NarrativeOutput & { provider: string; model: string };

type EditorError =
  | { kind: "generate"; message: string; retryable: boolean }
  | { kind: "save"; message: string; retryable: boolean };

// Provenance for text a person wrote from scratch after AI drafting failed or
// wasn't wanted (docs/runbooks/ai-provider-failure.md step 5).
const MANUAL_PROVIDER = "manual";

const BLANK_MANUAL_DRAFT: NarrativeDraft = {
  executive_summary: "",
  recommended_approach: "",
  scope: "",
  assumptions_exclusions: [],
  next_steps: [],
  email_draft: "",
  provider: MANUAL_PROVIDER,
  model: "none",
};

const FOCUS =
  "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-lime-400";
const FIELD =
  "w-full rounded-md border border-navy-700 bg-navy-950 p-3 text-navy-50 disabled:opacity-75";
const LABEL = "mb-1 block text-sm text-navy-300";

// The API reports provider failures tersely ("Provider timeout"); say what
// happened in the user's terms. Status codes from apps/api/app/api/ai.py.
function describeGenerateError(
  err: unknown,
): Omit<EditorError, "kind"> & { canWriteManually: boolean } {
  const status = err instanceof ApiError ? err.status : null;
  switch (status) {
    case 504:
      return {
        message: "The AI provider took too long to respond.",
        retryable: true,
        canWriteManually: true,
      };
    case 502:
      return {
        message: "The AI provider sent back a draft we couldn't use.",
        retryable: true,
        canWriteManually: true,
      };
    case 500:
      return {
        message: "AI drafting isn't set up on this server.",
        retryable: false,
        canWriteManually: true,
      };
    case 400:
      return {
        message: "Add at least one package line before drafting.",
        retryable: false,
        canWriteManually: false,
      };
    case 403:
      return {
        ...describeError(err, { action: "draft proposal narratives" }),
        canWriteManually: false,
      };
    default:
      return {
        message: "Couldn't reach the AI provider.",
        retryable: true,
        canWriteManually: true,
      };
  }
}

function providerLabel(provider: string): string {
  switch (provider) {
    case "openrouter":
      return "Generated by OpenRouter";
    case "ollama":
      return "Generated locally with Ollama";
    case MANUAL_PROVIDER:
      return "Written manually";
    default:
      return `Generated by ${provider}`;
  }
}

interface AiNarrativeEditorProps {
  version: api.ProposalVersion;
  editable: boolean;
  token: string;
  onSaved: (v: api.ProposalVersion) => void;
}

export function AiNarrativeEditor({
  version,
  editable,
  token,
  onSaved,
}: AiNarrativeEditorProps) {
  const [draft, setDraft] = useState<NarrativeDraft | null>(
    version.narrative_json || null,
  );
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<EditorError | null>(null);
  const [canWriteManually, setCanWriteManually] = useState(false);

  const isDirty =
    draft !== null &&
    JSON.stringify(draft) !== JSON.stringify(version.narrative_json);

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const res = await api.generateProposalNarrative(token, version.id);
      setDraft({
        executive_summary: res.executive_summary,
        recommended_approach: res.recommended_approach,
        scope: res.scope,
        assumptions_exclusions: res.assumptions_exclusions,
        next_steps: res.next_steps,
        email_draft: res.email_draft,
        provider: res.provider,
        model: res.model,
      });
    } catch (err) {
      // Whatever is already in the editor stays put; a failed draft never
      // clears existing content (runbook step 5).
      const described = describeGenerateError(err);
      setError({
        kind: "generate",
        message: described.message,
        retryable: described.retryable,
      });
      setCanWriteManually(described.canWriteManually);
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!draft) return;
    setSaving(true);
    setError(null);
    try {
      const updated = await api.saveProposalVersionNarrative(
        token,
        version.id,
        draft,
      );
      setDraft(updated.narrative_json);
      onSaved(updated);
    } catch (err) {
      setError({
        kind: "save",
        ...describeError(err, { action: "save the narrative" }),
      });
    } finally {
      setSaving(false);
    }
  };

  const handleWriteManually = () => {
    setError(null);
    setDraft(BLANK_MANUAL_DRAFT);
  };

  const updateField = <K extends keyof api.NarrativeOutput>(
    field: K,
    value: api.NarrativeOutput[K],
  ) => {
    if (!draft) return;
    setDraft({ ...draft, [field]: value });
  };

  const hasLines = version.content_json.lines.length > 0;

  if (!editable && !version.narrative_json) {
    return null;
  }

  const showWriteManually =
    editable && error?.kind === "generate" && canWriteManually && !draft;

  return (
    <div className="mt-8 rounded-lg border border-navy-800 bg-navy-900 p-4 sm:p-6">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <h2 className="text-xl font-semibold text-navy-50">
          AI proposal narrative
        </h2>
        {editable && (
          <button
            type="button"
            onClick={() => void handleGenerate()}
            disabled={!hasLines || generating}
            className={`min-h-10 rounded-md border border-lime-400/30 bg-navy-800 px-4 py-2 text-lime-400 transition-colors duration-150 hover:bg-navy-700 disabled:cursor-not-allowed disabled:opacity-50 ${FOCUS}`}
          >
            {generating ? "Generating…" : "Generate draft"}
          </button>
        )}
      </div>

      {error && (
        <div
          role="alert"
          className="mb-6 flex flex-col gap-3 rounded-md border border-red-900 bg-red-950/40 p-4 sm:flex-row sm:items-center sm:justify-between"
        >
          <div>
            <p className="text-sm text-red-200">{error.message}</p>
            {showWriteManually && (
              <p className="mt-1 text-sm text-navy-300">
                You can try again, or write the narrative yourself.
              </p>
            )}
          </div>
          <div className="flex shrink-0 flex-wrap gap-2">
            {error.retryable && (
              <button
                type="button"
                onClick={() =>
                  void (error.kind === "save" ? handleSave() : handleGenerate())
                }
                className={`min-h-10 rounded-md border border-navy-700 bg-navy-800 px-4 text-sm font-medium text-navy-50 transition-colors duration-150 hover:bg-navy-700 ${FOCUS}`}
              >
                Retry
              </button>
            )}
            {showWriteManually && (
              <button
                type="button"
                onClick={handleWriteManually}
                className={`min-h-10 rounded-md border border-navy-700 px-4 text-sm font-medium text-navy-50 transition-colors duration-150 hover:border-lime-400 ${FOCUS}`}
              >
                Write it yourself
              </button>
            )}
          </div>
        </div>
      )}

      {draft && (
        <div className="space-y-6">
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-md bg-navy-950 p-3 text-sm text-navy-300">
            <div>{providerLabel(draft.provider)}</div>
            {draft.provider !== MANUAL_PROVIDER && (
              <div className="text-amber-300">
                Draft AI Content — Requires human review
              </div>
            )}
          </div>

          <div className="space-y-4">
            <div>
              <label htmlFor="narrative-executive-summary" className={LABEL}>
                Executive summary
              </label>
              <textarea
                id="narrative-executive-summary"
                value={draft.executive_summary}
                onChange={(e) =>
                  updateField("executive_summary", e.target.value)
                }
                disabled={!editable}
                className={`${FIELD} min-h-[100px]`}
              />
            </div>
            <div>
              <label htmlFor="narrative-recommended-approach" className={LABEL}>
                Recommended approach
              </label>
              <textarea
                id="narrative-recommended-approach"
                value={draft.recommended_approach}
                onChange={(e) =>
                  updateField("recommended_approach", e.target.value)
                }
                disabled={!editable}
                className={`${FIELD} min-h-[100px]`}
              />
            </div>
            <div>
              <label htmlFor="narrative-scope" className={LABEL}>
                Scope
              </label>
              <textarea
                id="narrative-scope"
                value={draft.scope}
                onChange={(e) => updateField("scope", e.target.value)}
                disabled={!editable}
                className={`${FIELD} min-h-[100px]`}
              />
            </div>

            <StringListEditor
              label="Assumptions and exclusions"
              items={draft.assumptions_exclusions}
              editable={editable}
              onChange={(items) => updateField("assumptions_exclusions", items)}
            />

            <StringListEditor
              label="Next steps"
              items={draft.next_steps}
              editable={editable}
              onChange={(items) => updateField("next_steps", items)}
            />

            <div>
              <label htmlFor="narrative-email-draft" className={LABEL}>
                Email draft
              </label>
              <textarea
                id="narrative-email-draft"
                value={draft.email_draft}
                onChange={(e) => updateField("email_draft", e.target.value)}
                disabled={!editable}
                className={`${FIELD} min-h-[150px] font-mono text-sm`}
              />
            </div>
          </div>

          {editable && (
            <div className="flex justify-end pt-4">
              <button
                type="button"
                onClick={() => void handleSave()}
                disabled={!isDirty || saving}
                className={`min-h-10 rounded-md bg-lime-400 px-6 py-2 font-medium text-navy-950 transition-colors duration-150 hover:bg-lime-300 disabled:bg-navy-700 disabled:text-navy-300 disabled:opacity-50 ${FOCUS}`}
              >
                {saving ? "Saving…" : "Save"}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function StringListEditor({
  label,
  items,
  editable,
  onChange,
}: {
  label: string;
  items: string[];
  editable: boolean;
  onChange: (items: string[]) => void;
}) {
  return (
    <fieldset>
      <legend className="mb-2 block text-sm text-navy-300">{label}</legend>
      <div className="space-y-2">
        {items.map((item, idx) => (
          <div key={idx} className="flex gap-2">
            <input
              type="text"
              value={item}
              aria-label={`${label}, item ${idx + 1}`}
              onChange={(e) => {
                const newItems = [...items];
                newItems[idx] = e.target.value;
                onChange(newItems);
              }}
              disabled={!editable}
              className="min-w-0 flex-1 rounded-md border border-navy-700 bg-navy-950 p-2 text-navy-50 disabled:opacity-75"
            />
            {editable && (
              <button
                type="button"
                onClick={() => {
                  const newItems = [...items];
                  newItems.splice(idx, 1);
                  onChange(newItems);
                }}
                className={`inline-flex min-h-10 min-w-10 shrink-0 items-center justify-center rounded-md border border-navy-700 bg-navy-800 text-red-400 transition-colors duration-150 hover:bg-navy-700 ${FOCUS}`}
                aria-label={`Remove ${label.toLowerCase()} item ${idx + 1}`}
              >
                ×
              </button>
            )}
          </div>
        ))}
        {editable && (
          <button
            type="button"
            onClick={() => onChange([...items, ""])}
            className={`min-h-10 rounded-md text-sm text-lime-400 hover:text-lime-300 ${FOCUS}`}
          >
            + Add item
          </button>
        )}
      </div>
    </fieldset>
  );
}
