const PROVIDER_NAMES: Record<string, string> = {
  openrouter: "OpenRouter",
  ollama: "Ollama",
};

function providerName(provider: string): string {
  return PROVIDER_NAMES[provider] ?? provider;
}

/** "openrouter timeout" → "OpenRouter timeout" (ADR-005 fallback reasons). */
export function formatFallbackReason(reason: string): string {
  const [provider, ...rest] = reason.split(" ");
  return [providerName(provider), ...rest].join(" ");
}

/** Who wrote a draft, including why it came from the fallback provider. */
export function provenanceLabel(
  provider: string,
  fallbackReason?: string | null,
): string {
  const base =
    provider === "openrouter"
      ? "Generated by OpenRouter"
      : provider === "ollama"
        ? "Generated locally with Ollama"
        : `Generated by ${provider}`;
  return fallbackReason
    ? `${base} (fallback: ${formatFallbackReason(fallbackReason)})`
    : base;
}
