import { describe, expect, it } from "vitest";

import { formatFallbackReason, provenanceLabel } from "./provenance";

describe("provenance", () => {
  it("names the provider that wrote the draft", () => {
    expect(provenanceLabel("openrouter")).toBe("Generated by OpenRouter");
    expect(provenanceLabel("ollama")).toBe("Generated locally with Ollama");
    expect(provenanceLabel("fake", null)).toBe("Generated by fake");
  });

  it("explains a fallback", () => {
    expect(provenanceLabel("ollama", "openrouter timeout")).toBe(
      "Generated locally with Ollama (fallback: OpenRouter timeout)",
    );
    expect(formatFallbackReason("openrouter unavailable")).toBe(
      "OpenRouter unavailable",
    );
    expect(formatFallbackReason("custom down")).toBe("custom down");
  });
});
